export const GET_CODE_PARAM = 'GET_CODE_PARAM'
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN'
export const GET_USER_DETAILS = 'GET_USER_DETAILS'
export const GET_CITY_DETAILS = 'GET_CITY_DETAILS'
export const GET_FORECAST_DETAILS = 'GET_FORECAST_DETAILS'

